[FIREBASE]
TYPE = "service_account"
PROJECT_ID = "writing-comparison"
PRIVATE_KEY_ID = "204fe8b59bb168dc5738db8d55c248d561b7bfaf"
PRIVATE_KEY = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDM2+vItkEFKYaW
0585oUbfi9/WJhMUpGyEVj3ODRX8LgofG/mYfng306ngJCsK5q5Kbcgki0vT+D7m
MM5fiyFWEmT9hMOEuyMZ5tvIMfkOCiP8qTbeKVjnF3cA2NgR/zEY6buPfSt0aYPw
WQiCB+XPSTL6wGVqUUYC3ruq7m2ZhoGru36dJDIUcDeBXa49XK3ABWToVcItQTbc
qz2+E2cSeX/5BFYUyGKFnZ3CaY5w4FyviqWegq2y685i1zEbuKrAzAHFdcX6imM1
2EE2nOz0HAKMj5hrRlKkzupIED1qRDby9Oh1Hi3zjnBIW7mKpoo0jGvwOsms4oP9
+emzGahpAgMBAAECggEASWMhWOI9cbF6Fw8Rk84cOxn7Ila6cCMlAtV4R5f1f8Uo
eBOH+yKXQ3yOdw7N4pZX6q7gS4MhM3rTYZgrXhvT4ecuCYnllueJQA6tPk70pxxn
3uvpjXWndQW5anLEGNJgDsowmEshZY8lJlVm0Fou7+6LljuVORyLZZzQAwBt/9iF
BihaOmIYoXMIbph9FbpCKVGaDLYSk+ouL66AsbV8uENwah7jdm9QRA5+sRg8LbPz
+AdDJIJYaiBQvPYUO6vQ+wNA9IVi+KF1+TUOoMeFTfIV+oF+qxzkbi8eL6iQ7p4h
ZIdlKXYz4iMM+RrT3eR5UWSyb9QRQV0kDuTWJw0mlwKBgQDnehh406ZxEyUnBwu5
TqkS0q6SOl2xFPw/W0HlF3sZ+yC8U1bqnIDhTxRxu6M1DCKmAMYyh81lsPwslVgi
a4MVhyVEOSthV8WaKkmFfRq/Lyx91pzXydBIiRRoMVy5R6jrmE97eLZJDk+4dOeq
QYDvcwZHQ27YmWi776opU1UvGwKBgQDij+uKkZO/TE5PQxCQK89DuJfmWj8PWEdi
7EIgMVSp/xmOk5Quc+HIt8HIe3tSIzYyNDxon5CpLIZZciIahwNjz1QqErZLVpUx
hUHk6p/MemsiEPFh0ZoSS+LDC+ze2XeLl/ZG+HRgISLg+eif2AeqRhyZa0NiQszq
M5rD8kbKywKBgHCE4Dpzn5edl9S1zxQf0X3t3aAFMR/wNIHTqV9kH5nMgegplrlq
pBdhqm1yqW4S3RDWlYFglA5Xju1ZF0N8AXdIf2v/Yj/qO4qp/Z0e6A6BLt5ooUsf
tdhckgfn3svNsqX7Hr/FOM6gX04pvab8OmGrByVC+THeuJOKd6uo72J7AoGBANgW
YpZAcQW01r/cfDC1yDKUHjTzgE+3aCbepdckldap24tUELIZjpCtSuNXevCFawyJ
K9Cx1/yy3dTz+bkJat9IgMK8JChJBXU83vNiIFWbsRDFziP5ERVAUaCsgBiwm8eF
gbyA/iYtlKG1Wf0Sw4TQ6DgfyR4wDleWLpeTPZfvAoGBAMVcPiVZYgypU5b6yUIP
zvooAvVW91na3W8GZ9S6eSDKxzGTzt9sl20IVZkuUPCANLDcHQyKXQPjEoqeuM3Z
cnmSgHPtl7Vn73LFQY6m+aEU4kUX0hQgxRkQ833qWmmMNNaTd1lWmTfEY6t6OAA2
BD5Cfz+gWdrQ6fcJmCzutFn2
-----END PRIVATE KEY-----"""
CLIENT_EMAIL = "firebase-adminsdk-fbsvc@writing-comparison.iam.gserviceaccount.com"
CLIENT_ID = "109764193759408901069"
AUTH_URI = "https://accounts.google.com/o/oauth2/auth"
TOKEN_URI = "https://oauth2.googleapis.com/token"
AUTH_PROVIDER_X509_CERT_URL = "https://www.googleapis.com/oauth2/v1/certs"
CLIENT_X509_CERT_URL = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc@writing-comparison.iam.gserviceaccount.com"
STORAGE_BUCKET = "writing-comparison.firebasestorage.app"  # ✅ Use exactly as shown in Firebase Console
[CREDENTIALS]
School_A = "passwordA"
School_B = "passwordB"
adminkbrown = "115413Gtcs@"

